### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by maitrey0da** [philn/Radioplayer#1] opened 2016-04-29 08:31 UTC
Hello,

Thanks for this radio player, with Last.fm supports :-)

I have somes troubles with the Web remote on port 5000.

A log 
`127.0.0.1 - - [29/Apr/2016 10:25:01] "GET / HTTP/1.1" 500 -`

**Comment by philn** [comment] 2016-04-29 16:33
Can you git pull and try again please? A traceback should be reported in the browser :)

**Comment by maitrey0da** [comment] 2016-04-29 19:09
I'm in.

The debug log 
```
 ⮀ radioplayer                                                                                                                                                                                         ⮂  
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.linux-x86_64/egg/radioplayer/web_remote.py", line 25, in _start
    app.run(host='0.0.0.0', debug=True)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 689, in run_simple
    reloader_type)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/_reloader.py", line 242, in run_with_reloader
    signal.signal(signal.SIGTERM, lambda *args: sys.exit(0))
ValueError: signal only works in main thread

FIP: ♫ Prince - Digital Garden ♫
```


The end
```
curl -I http://127.0.0.1:5000/                                                                                                                                                                     ⮂  
curl: (7) Failed to connect to 127.0.0.1 port 5000: Connexion refusée
```

**Comment by philn** [comment] 2016-04-30 07:21
Hum... which version of Flask do you use? I can't reproduce this issue, and had to revert the commit enabling debug because that doesn't work on the threaded server :/

**Comment by maitrey0da** [comment] 2016-05-02 08:15
The Flask's version: 0.10.1

**Comment by philn** [comment] 2016-05-02 10:04
Well, I think I'll ditch this dependency on Flask and use plain CGI :) Is this lack of web UI a blocker for you in the short term?

**Comment by maitrey0da** [comment] 2016-05-02 10:10
No, I reported this issue in order to begin a discussion with you  :) (like #2 )

**Comment by philn** [comment] 2017-06-23 12:27
I've just switched the web_remote to aiohttp, seems to work. It's very minimalistic compared to the GTK+ UI, I'll try to improve it a bit :)

**Comment by philn** [comment] 2017-06-23 12:35
I'll close this now, the issue was valid when the  web_remote was based on Flask, which is no longer the case :)

**Closed by philn** 2017-06-23 12:35 UTC
